export const initialBatches = [
  {
    id: "1",
    name: "SQL Basics To Advanced Mastery Course",
    status: "Published",
    startDate: "20 Jul 2024",
    endDate: "28 Jul 2024",
    price: "₹ 2,000",
    validity: "180 days",
    imageUrl: "/batchesimg/image1.png",
  },
  {
    id: "2",
    name: "30 Days Of Javascript Challenge",
    status: "Unpublished",
    startDate: "13 Jul 2024",
    endDate: "12 Aug 2024",
    price: "₹ 6,000",
    validity: "33 days",
    imageUrl: "/batchesimg/image2.png",
  },
  {
    id: "3",
    name: "Interview Preparation With Javascript 2.0",
    status: "Published",
    startDate: "02 Aug 2024",
    endDate: "15 Sep 2024",
    price: "₹ 10,000",
    validity: "365 days",
    imageUrl: "/batchesimg/image3.png",
  },
  {
    id: "4",
    name: "React Basics Course",
    status: "Published",
    startDate: "01 Aug 2024",
    endDate: "31 Aug 2024",
    price: "₹ 5,000",
    validity: "90 days",
    imageUrl: "/batchesimg/image4.png",
  },
  {
    id: "5",
    name: "Advanced CSS Techniques",
    status: "Unpublished",
    startDate: "05 Aug 2024",
    endDate: "25 Aug 2024",
    price: "₹ 3,000",
    validity: "60 days",
    imageUrl: "/batchesimg/image5.png",
  },
  {
    id: "6",
    name: "Node.js and Express",
    status: "Published",
    startDate: "10 Aug 2024",
    endDate: "30 Aug 2024",
    price: "₹ 7,000",
    validity: "120 days",
    imageUrl: "/batchesimg/image1.png",
  },
  {
    id: "7",
    name: "Python for Data Science",
    status: "Published",
    startDate: "15 Aug 2024",
    endDate: "05 Sep 2024",
    price: "₹ 8,000",
    validity: "180 days",
    imageUrl: "/batchesimg/image2.png",
  },
  {
    id: "8",
    name: "Machine Learning with Python",
    status: "Published",
    startDate: "20 Aug 2024",
    endDate: "10 Sep 2024",
    price: "₹ 9,000",
    validity: "200 days",
    imageUrl: "/batchesimg/image3.png",
  },
  {
    id: "9",
    name: "Full Stack Development",
    status: "Unpublished",
    startDate: "25 Aug 2024",
    endDate: "15 Sep 2024",
    price: "₹ 10,000",
    validity: "365 days",
    imageUrl: "/batchesimg/image4.png",
  },
  {
    id: "10",
    name: "Introduction to Databases",
    status: "Published",
    startDate: "01 Sep 2024",
    endDate: "21 Sep 2024",
    price: "₹ 2,000",
    validity: "90 days",
    imageUrl: "/batchesimg/image5.png",
  },
  {
    id: "11",
    name: "Big Data Analytics",
    status: "Unpublished",
    startDate: "05 Sep 2024",
    endDate: "25 Sep 2024",
    price: "₹ 15,000",
    validity: "365 days",
    imageUrl: "/batchesimg/image1.png",
  },
  {
    id: "12",
    name: "Cloud Computing Fundamentals",
    status: "Published",
    startDate: "10 Sep 2024",
    endDate: "30 Sep 2024",
    price: "₹ 12,000",
    validity: "180 days",
    imageUrl: "/batchesimg/image2.png",
  },
  {
    id: "13",
    name: "Blockchain Basics",
    status: "Unpublished",
    startDate: "15 Sep 2024",
    endDate: "05 Oct 2024",
    price: "₹ 20,000",
    validity: "365 days",
    imageUrl: "/batchesimg/image3.png",
  },
  {
    id: "14",
    name: "Cybersecurity Essentials",
    status: "Published",
    startDate: "20 Sep 2024",
    endDate: "10 Oct 2024",
    price: "₹ 18,000",
    validity: "365 days",
    imageUrl: "/batchesimg/image4.png",
  },
  {
    id: "15",
    name: "AI and Robotics",
    status: "Published",
    startDate: "25 Sep 2024",
    endDate: "15 Oct 2024",
    price: "₹ 25,000",
    validity: "365 days",
    imageUrl: "/batchesimg/image5.png",
  },
];
